version: '3'
services:
  llm_homology_api:
    build:
      context: .
      args:
        VCS_REF: ${VCS_REF}
        VERSION: ${VERSION}
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    env_file:
      - .docker_compose_env
    volumes:
      - /scratch/sprot/sprot_esm_650m_faiss:/models/sprot_esm_650m_faiss
      - /scratch/sprot/sprot_esm_650m_faiss.index:/models/sprot_esm_650m_faiss.index
